config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  get 'search', to: 'search#search'
  root 'feeds#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    def initialize(user)
      user ||= User.new # guest user (not logged in)
      
      if user.superadmin_role?
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
require 'elasticsearch/model'

class Entry < ApplicationRecord
  belongs_to :feed
  
  #elastic
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english', index_options: 'offsets'
      indexes :content, analyzer: 'english'
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'content']
          }
        }
      }
    )
  end
end

# Delete the previous Entrys index in Elasticsearch
Entry.__elasticsearch__.client.indices.delete index: Entry.index_name rescue nil

# Create the new index with the new mapping
Entry.__elasticsearch__.client.indices.create \
  index: Entry.index_name,
  body: { settings: Entry.settings.to_hash, mappings: Entry.mappings.to_hash }

# Index all Entry records from the DB to Elasticsearch
Entry.import

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :entries, dependent: :destroy
  validates_presence_of :name, :url, :description
  after_save :clear_cache

  def clear_cache
    $redis.del "feeds"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_feed, only: :index

  def index
    @entries = @feed.entries.order('published desc')
  end

  #def index
  #  @entries = @feed.entries.order('published desc')
  #end

  def show
    @entry = Entry.find(params[:id])
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController 
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  

  def index
   
    feeds =  $redis.get("feeds")
    if feeds.nil?
      feeds = Feed.all.to_json
      $redis.set("feeds", feeds)
      $redis.expire("feeds",3.hour.to_i)
    end
    @feeds = JSON.load feeds
  end
   
  def show
    @feed
    authorize! :edit, @feed
  end

  def new 
    @feed = Feed.new
  end

  def edit 
    @feed
    authorize! :edit, @feed
  end
  
  def create
    @feed = Feed.create(feed_params)
    redirect_to feeds_path
  end

  def update
    @feed.update(feed_params)
    @feed
  end

  def destroy 
    @feed.destroy
    redirect_to feeds_path
  end

  private


  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params[:feed].permit(:name, :url, :description)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @entries = []
    else
      @entries = Entry.search params[:q]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/entries/index.html.erb
# app/views/entries/index.html.erb
<div class="container">
  <% @entries.each do |entry| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to entry.title, entry %> - <i> published <%= time_ago_in_words(entry.published) %> ago.</i>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/show.html.erb
# app/views/entries/show.html.erb
<div class="container">
  <h3><%= link_to @entry.title, @entry.url %></h3>
  <i>published on <%= @entry.published %> by <%= @entry.author %></i>
  <p>
    <%= if @entry.content.nil? then  @entry.content else @entry.content.html_safe end %>
  </p>
</div>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
<% if feed.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

    <ul>
    <% feed.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :feed_name %>
</div>

<div class="field">
  <%= form.label :url %>
  <%= form.text_field :url, id: :feed_url %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description, id: :feed_description %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed['name'] %></td>
        <td><%= feed['url'] %></td>
        <td><%= feed['description'] %></td>
        <td><%= link_to 'Show', feed_path(feed['id']) %></td>
        <% if current_user && current_user.superadmin_role? && current_user.admin_role? %>
          <td><%= link_to 'Edit', edit_feed_path(feed['id']) %></td>
          <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.superadmin_role? && current_user.admin_role? %>
  <%= link_to 'New feed', new_feed_path %>
<% end %>
<%= link_to 'Search', search_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<%= link_to 'Entries', entries_path(@feed) %> |

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <li><%= link_to 'Home', root_path %></li>
    <ul>
      <% if user_signed_in? %>
        <li>
            <p><%= current_user.name %></p>
          <ul>
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>

    <title>Sneakerss2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<h1>entries Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <h3>
        <%= link_to entry.try(:highlight).try(:title) ? entry.highlight.title[0].html_safe : entry.title,
          controller: "entries",
          action: "show",
          id: entry._id%>
      </h3>
      <% if entry.try(:highlight).try(:text) %>
        <% entry.highlight.text.each do |snippet| %>
          <p><%= snippet.html_safe %>...</p>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>